controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

search_users:
    path: /search-users
    controller: App\Controller\UserController::searchUsers
    methods: ['GET']
